### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by cyouh95** [AlexMV3/Project-Codecademy-SQL#1]
### Criteria 1: Report
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ Excellent job presenting your query results and thoroughly addressing each question! 
 
### Criteria 2: Query Accuracy
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ All queries accurately retrieve the data intended.
 
### Criteria 3: Query Formatting
* _Score Level:_ 3 (Meets Expectations)
* _Comment(s):_ Overall great job on the formatting! Although one thing that may help improve readability of code is to consistently use spaces instead of tabs for the indentation (e.g. [[x](https://github.com/AlexMV3/Project-Codecademy-SQL/blob/94680e7c23bc24c0b280a1a2371448cd5cd72861/code.sql.txt#L25-L71)]). If you're not already, try using a text editor such as [these](https://www.codecademy.com/articles/text-editors-sublime-atom), where you can configure it to insert spaces when you hit the `tab` key.  

   Separately, the [style guide](https://s3.amazonaws.com/codecademy-content/programs/learn-sql-from-scratch/SQL+Style+Guide+for+Learn+SQL+from+Scratch.pdf) also recommends that you refer to columns by their col number in `GROUP BY` or `ORDER BY` clause (e.g. [[x](https://github.com/AlexMV3/Project-Codecademy-SQL/blob/94680e7c23bc24c0b280a1a2371448cd5cd72861/code.sql.txt#L150)]).
 
### Criteria 4: Understanding underlying concepts and terminology
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ Report demonstrates clear understanding​ of churn rates.
 
 ### Overall Score: 15/16
Well done on this project! You definitely have a good understanding of churn rates as well as great grasp on all the SQL commands. 

The queries are well-written, and your presentation slides are beautifully put together and showcases the results nicely! I also really like how you've plotted out the trend in churn rates with the line graphs! (although it seems you may want to double check the placement of the `churn_rate_30` and `churn_rate_87` lines on your last slide)

A couple more tips:
- [Here](https://github.com/AlexMV3/Project-Codecademy-SQL/blob/94680e7c23bc24c0b280a1a2371448cd5cd72861/code.sql.txt#L9-L13): Alternatively, we could more efficiently get both min and max date in a single query:
```sql
SELECT MIN(subscription_start) AS min_date,
  MAX(subscription_end) AS max_date
FROM subscriptions;
```
- [Here](https://github.com/AlexMV3/Project-Codecademy-SQL/blob/94680e7c23bc24c0b280a1a2371448cd5cd72861/code.sql.txt#L18-L20): The `SELECT DISTINCT` statement would also be great to use:
```sql
SELECT DISTINCT segment
FROM subscriptions;
```
 
As a further challenge, continue exploring different SQL commands and test writing queries using this dataset. For example, see if you can modify this code to support a large number of segments. Have fun! :)

**Comment by AlexMV3** [comment]
Thank you! Great feedback.
